export * from "@components/Header/Header";
export * from "@components/Footer/Footer";
export * from "@components/Hero/Hero";
export * from "@components/Coins/Coins"
export * from "@components/FAQList/FAQList"
export * from "@components/Sponsors/Sponsors"
export * from "@components/Beneficios/Beneficios"
export * from "@components/Contact/Contact"
export * from "@components/Rail/Rail"
export * from "@components/TablaPrecios/TablaPrecios"